name: E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    name: E2E Tests (${{ matrix.browser }})
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd frontend
          npx playwright install --with-deps ${{ matrix.browser }}

      - name: Build frontend
        run: |
          cd frontend
          npm run build
        env:
          NODE_ENV: production

      - name: Run E2E Tests
        run: |
          cd frontend
          npx playwright test --project=${{ matrix.browser }}
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results-${{ matrix.browser }}
          path: frontend/test-results/
          retention-days: 7

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: frontend/playwright-report/
          retention-days: 7

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.browser }}
          path: frontend/test-results/screenshots/
          retention-days: 7

  smoke-tests:
    name: Smoke Tests (Fast)
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Playwright Browsers (Chromium only)
        run: |
          cd frontend
          npx playwright install --with-deps chromium

      - name: Build frontend
        run: |
          cd frontend
          npm run build
        env:
          NODE_ENV: production

      - name: Run Smoke Tests
        run: |
          cd frontend
          npx playwright test smoke.spec.ts --project=chromium
        env:
          CI: true

      - name: Upload smoke test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results
          path: frontend/test-results/
          retention-days: 3

  mobile-tests:
    name: Mobile E2E Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd frontend
          npx playwright install --with-deps chromium

      - name: Build frontend
        run: |
          cd frontend
          npm run build
        env:
          NODE_ENV: production

      - name: Run Mobile Tests
        run: |
          cd frontend
          npx playwright test responsive-design.spec.ts --project="Mobile Chrome"
        env:
          CI: true

      - name: Upload mobile test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mobile-test-results
          path: frontend/test-results/
          retention-days: 7
